/**
 * npm run env:local [-- --force] [-- --stdout]
 *
 * Writes .env.local for the LOCAL Supabase stack (`supabase start`) from
 * `supabase status`. These are the well-known local development keys, not
 * production secrets. Refuses to overwrite an existing .env.local unless
 * --force is given, so real values are never clobbered.
 * --stdout prints KEY=value lines instead (used by CI to fill $GITHUB_ENV).
 */
import { execSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';

const raw = execSync('npx supabase status -o env', { encoding: 'utf8' });
const status = Object.fromEntries(
  raw
    .split('\n')
    .map((line) => /^([A-Z0-9_]+)="?(.*?)"?$/.exec(line.trim()))
    .filter((m): m is RegExpExecArray => m !== null)
    .map((m) => [m[1], m[2]]),
) as Record<string, string | undefined>;

const need = ['API_URL', 'PUBLISHABLE_KEY', 'SECRET_KEY'] as const;
for (const k of need) {
  if (!status[k]) throw new Error(`supabase status did not report ${k}. Is the local stack running?`);
}

const lines = [
  `NEXT_PUBLIC_SUPABASE_URL=${status.API_URL}`,
  `NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${status.PUBLISHABLE_KEY}`,
  'NEXT_PUBLIC_SITE_URL=http://localhost:3000',
  `SUPABASE_SECRET_KEY=${status.SECRET_KEY}`,
  'SUPABASE_STORAGE_BUCKET=images',
  'DEFAULT_EVENT_TIMEZONE=Pacific/Auckland',
];

if (process.argv.includes('--stdout')) {
  process.stdout.write(`${lines.join('\n')}\n`);
} else if (existsSync('.env.local') && !process.argv.includes('--force')) {
  console.error('.env.local already exists. Re-run with --force to replace it with local stack values.');
  process.exit(1);
} else {
  writeFileSync('.env.local', `# Local Supabase stack (generated by npm run env:local)\n${lines.join('\n')}\n`);
  console.log('Wrote .env.local for the local Supabase stack.');
}
